### PR TITLE
Added 18 new Channels

### PR DESCRIPTION
**Pull request by sukhchainn**
I added 18 new channels and The categories are in double quotes so that they will be rearranged by the person who is in-charge of further categorizing this list.

### CODE REVIEW

**Comment by sukhchainn** [comment]
@ErikCH  can you tell me where is the conflict? I don't understand this.
Even when I pushed the changes it still says that there are conflicts.

**Comment by scanf** [comment]
👍 Looks like you fixed it but you can read up more on merge conflicts [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github) from the GitHub help pages https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

**Comment by sukhchainn** [comment]
@ErikCH I resolved the conflicts, now it's ready for merge.

**Comment by ErikCH** [comment]
I like this idea, and I appreciate the help adding these categories, but now we have another section at the bottom that doesn't really flow with the rest of the page. And some of those channels are duplicates of the ones on top. It feels like if we are going to add more categories then we need to move them to the english section, remove the duplicates and categorize it that way.

What do you think @scanf and @sukhchainn ?

**Comment by sukhchainn** [comment]
Well, my entries are not duplicates.
I checked them through ctr+F utility and they weren't repeating. I will
create a grep command and test all the entries. This way we will have a
complete list of duplicates but the problem is that we still need to check
these entries manually to find out which category they belong to.

**Comment by scanf** [comment]
@sukhchainn I think the duplication is on the categories. For ex. you added `Coder's Tape` which is an English channel. It should be added to the English category but instead, you created a new section at the bottom. Does it make sense? If not try looking through the rendered file a couple of times.

**Comment by scanf** [comment]
@ErikCH  I don't really have any opinions on that really. Having something consistent would be nice. So maybe @sukhchainn could update this pr to look match the style of the existing file?

**Comment by ErikCH** [comment]
Well, for example javidx is also in the list above. So if we want to do this, this needs to be where the English channels are, and those channels need to be removed from the list of normal tutorials...

**Comment by sukhchainn** [comment]
Hello Guys, I'm going to refactor this entire list and divide them according to the technologies they specialize in. The main Three categories will be (JavaScript, PHP, C/C++). I hope you don't have any problem with that.

**Comment by scanf** [comment]
@sukhchainn To be honest, it would be more interesting to continue grouping by general category. Languages could be represented in other ways like tags. The way I would use this list is f. ex. to look for topics like game development, information, etc. I don't think I would specifically use it to look up language x.

**Comment by ErikCH** [comment]
I agree with @scanf - perhaps more like what I see in the Arabic section

**Comment by sukhchainn** [comment]
Ok, Let's just say we do all of them?

I will sort the channels based on C/C++, PHP, JavaScript and other categories that are present in Arabic section.

**Comment by ErikCH** [comment]
Yeah that would work @sukhchainn . The categories they made are Programming Tutorials, Web Development, Networking & Security etc...

**Comment by sukhchainn** [comment]
@ErikCH and @scanf , I have sorted the list manually name-wise for now for issue #85 , because writing automation script was taking a lot of time and there are a lot of essential features pending to be implemented in the script. I also have to manually check every YouTube channel and I'm mostly working on this only on weekends. I hope I'll be able to complete the script by Monday.

The script I'm working on detects lines containing "$Important" and doesn't change them until the flag "--unImportant" or "-ui" is provided. I'm making it as portable as possible so it's going to take a few days more.

**Comment by scanf** [comment]
I just wanted to follow up, I won't be able to help out here due to other obligations but I look forward to seeing it merged when @ErikCH is happy with it.

Thanks.

**Comment by ErikCH** [comment]
@scanf No problem thanks. @sukhchainn OK great

**Pull request closed without merging**
