### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DimitrisLK**
Added a new Youtuber

### CODE REVIEW

**Comment by ErikCH** [comment]
Add it to the bottom please :)

**Comment by DimitrisLK** [comment]
My bad, sorry about that

**Comment by ErikCH** [comment]
Just fix conflict :)

**Comment by DimitrisLK** [comment]
I've made a mistake, didn't see that the change I was trying make is already in the master branch(or was added recently). Can delete the pull request.

**Pull request closed without merging**
