### PR TITLE
Added new channels, Created 'Game Development' section

### PR DESCRIPTION
**Pull request by xmac11**
Added Telusko, kudvenkat, Awais Mirza in 'Tutorial'.
Added BBarters in 'Retired'.
Moved JavaBrains from 'Informational' to 'Tutorial'.

Created 'Game Development' section (moved there youtubers already existing in the list and added new ones too).
Added Jarvis Johnson in 'Software Entertainment'.

### CODE REVIEW

**Comment by sukhchainn** [comment]
I don't think that telusko should go in 'Tutorial' section, I think it's more fit for 'Informational' section because it has a few tutorial videos compared to informational videos.

**Comment by xmac11** [comment]
@sukhchainn For sure he is a mixture of informational and tutorial, and he may have leaned towards informational during the past few months. But just by skimming over his playlists the 'tutorial' word is eye-catching.
Even in the description of his channel he states: "I make free programming tutorials from beginner to advanced level. [...] Sometimes I make videos on motivation and take sessions with Tech industry experts".

**Comment by sukhchainn** [comment]
Well if @ErikCH is ok with it then it's no problem.

**Comment by ErikCH** [comment]
This is ok!

**Pull request merged**
