### PR TITLE
Adding TheDevWay

### PR DESCRIPTION
**Pull request by bsobbe**
I recently started my youtube channel and will go hard on the topics I added my channel.
Will appreciate if the request gets merged.

### CODE REVIEW

**Comment by xmac11** [comment]
> I recently started my youtube channel and will go hard on the topics I added my channel.
> Will appreciate if the request gets merged.

Hey, congratulations for your channel. 
You don't need to add it twice in different categories. 
`Up And Coming` is probably the best place.

**Comment by bsobbe** [comment]
@xmac11 ok thanks for the reply. I will change it now and will do another merge request

**Comment by bsobbe** [comment]
@xmac11  fixed it. if it looks fine, can we merge?

**Comment by xmac11** [comment]
> @xmac11 fixed it. if it looks fine, can we merge?

@bsobbe I don't own this repo, so I cannot merge. 

There still seem to be merge conflicts, so you should pull recent changes and resolve any conflicts. 

Or easier, just fork this repo again to have the latest changes, add your channel and submit a new PR.

Then I'm sure @ErikCH will merge it.

**Comment by bsobbe** [comment]
@xmac11  Thanks. I'm gonna close this and open a new one

**Pull request closed without merging**
