### PR TITLE
Add Andreas Kling

### PR DESCRIPTION
**Pull request by mandaputtra**
He is maintainer of [Serenity OS](https://github.com/SerenityOS/serenity) live streaming and he had some nice section called Comute Talk too when he answer subscriber questions / giving update / insight.

### CODE REVIEW

**Comment by mandaputtra** [comment]
And maybe we should change 'Amazing Developers Of YouTube' to 'Amazing Developers On YouTube' ? just my two cent, so it will revers to the developer that create video on YouTube, not the developer that create YouTube. Feedback welcome.

English are not my main language haha.

**Comment by ErikCH** [comment]
Sounds good, update the conflict and I'll merge. @mandaputtra  and yes, we can change to 'on' that's good

**Comment by mandaputtra** [comment]
Updated

**Comment by ErikHDev** [comment]
👍 LGTM

**Comment by ErikCH** [comment]
👍 LGTM

**Pull request merged**
